title: Guia FastAPI
description: Um guia para começar com FastAPI usando ferramentas como Poetry e Tortoise-ORM.

author: luikymagno
email: luikymagno@gmail.com

markdown: kramdown
theme: minima
plugins:
- jekyll-remote-theme
